services:
  ollama-server:
    container_name: ollama-server
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-model-cache:/root/.ollama
    restart: unless-stopped

volumes:
  ollama-model-cache:
